-- Insert 108 pre-verified cuerpo técnico members
CREATE TABLE IF NOT EXISTS ct_preverificados (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid(),
  nombre TEXT NOT NULL,
  nombre_normalizado TEXT NOT NULL,
  rol TEXT NOT NULL,
  datos_factura TEXT,
  usado BOOLEAN DEFAULT false,
  "usuarioCtId" TEXT,
  "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO ct_preverificados (id, nombre, nombre_normalizado, rol, datos_factura) VALUES
(gen_random_uuid(), 'Drazen Yugovich', 'drazen yugovich', 'Entrenador Nacional', 'Drazen Yugovich 5230897-9'),
(gen_random_uuid(), 'Sergio López', 'sergio lopez', 'Preparador Fisico', 'Club Olimpia 80029733-4'),
(gen_random_uuid(), 'CARLOS MARIA MIÑO', 'carlos maria mino', 'Entrenador Nacional', 'CLUB PETTIROSSI 80026142-9'),
(gen_random_uuid(), 'Abraham Acevedo', 'abraham acevedo', 'Preparador Fisico', 'Abaham Acevedo Ruc:2908065-7'),
(gen_random_uuid(), 'Daniel Emiliano Tomasi', 'daniel emiliano tomasi', 'Entrenador Extranjero', 'Colonias Unidas Basquet Club 80117060-5'),
(gen_random_uuid(), 'Arlés Stéfani', 'arles stefani', 'Entrenador Nacional', 'PRODE - RUC 80134805-6'),
(gen_random_uuid(), 'Franco Gutierrez', 'franco gutierrez', 'Entrenador Extranjero', 'PRODE 80134805-6'),
(gen_random_uuid(), 'Melina Gissel Pérez López', 'melina gissel perez lopez', 'Entrenador Nacional', 'Club Olimpia 80029733-4'),
(gen_random_uuid(), 'Emanuel Horacio Teves', 'emanuel horacio teves', 'Entrenador Extranjero', 'Lady Patricia Ortiz Rojas'),
(gen_random_uuid(), 'FABIAN QUIÑONEZ LOPEZ', 'fabian quinonez lopez', 'Utilero', 'CLUB SOL DE AMERICA 80028088-1'),
(gen_random_uuid(), 'EDISON ANIBAL ORTIZ ZARZA', 'edison anibal ortiz zarza', 'Entrenador Nacional', 'CLUB SOL DE AMERICA 800280881'),
(gen_random_uuid(), 'JUAN MALDONADO MARTINEZ', 'juan maldonado martinez', 'Fisio', 'CLUB SOL DE AMERICA 80028088-1'),
(gen_random_uuid(), 'JUAN MALDONADO MARTINEZ', 'juan maldonado martinez', 'Preparador Fisico', 'CLUB SOL DE AMERICA 80028088-1'),
(gen_random_uuid(), 'Ramón Ortiz', 'ramon ortiz', 'Entrenador Nacional', 'Lady Ortiz'),
(gen_random_uuid(), 'Jorge Luis Cortez Yucanovich', 'jorge luis cortez yucanovich', 'Entrenador Nacional', '5215062-3'),
(gen_random_uuid(), 'Crhistian Rodas', 'crhistian rodas', 'Asistente', 'Crhistian Rodas 3596545'),
(gen_random_uuid(), 'Carlos Maria Flores', 'carlos maria flores', 'Entrenador Nacional', 'Carlos Maria Flores 1266547-9'),
(gen_random_uuid(), 'María Carolina Cáraves', 'maria carolina caraves', 'Entrenador Nacional', 'Club Olimpia 80029733-4'),
(gen_random_uuid(), 'Rolando Ramón Coronel', 'rolando ramon coronel', 'Entrenador Nacional', 'Johanna Fritz 4082311-3'),
(gen_random_uuid(), 'Rolando Iván Paredes Mendieta', 'rolando ivan paredes mendieta', 'Asistente', 'Johanna Fritz Ruc 4082311-3'),
(gen_random_uuid(), 'Cesar Rallo', 'cesar rallo', 'Entrenador Nacional', 'Club Olímpia  Ruc 80029733-4'),
(gen_random_uuid(), 'Daihana Ines Galeano Fernández', 'daihana ines galeano fernandez', 'Fisio', 'Daihana Galeano 7010596-0'),
(gen_random_uuid(), 'Blas Pereira', 'blas pereira', 'Entrenador Nacional', 'Blas Pereia 3897553-0'),
(gen_random_uuid(), 'Victor Gracia', 'victor gracia', 'Preparador Fisico', 'Club Olimpia : 80029733-4'),
(gen_random_uuid(), 'Mauricio Ezequiel Gill Giménez', 'mauricio ezequiel gill gimenez', 'Entrenador Nacional', '1064574 - 8 Mercedes Gimenez'),
(gen_random_uuid(), 'Mauricio Ezequiel Gill Giménez', 'mauricio ezequiel gill gimenez', 'Entrenador Nacional', '1064574 - 8 Mercedes Gimenez'),
(gen_random_uuid(), 'Víctor Céspedes', 'victor cespedes', 'Asistente', 'Asoc de Ex alumnos del colegio San José  RUC 80027202-1'),
(gen_random_uuid(), 'Benjamin Ehrenfried', 'benjamin ehrenfried', 'Asistente', 'Asociación de Ex Alumnos del Colegio San José - 80027202-1'),
(gen_random_uuid(), 'JOSE TOMAS RIOS ZUNINI', 'jose tomas rios zunini', 'Entrenador Nacional', 'Jose Tomas Rios Zunini Ruc 2201531-0'),
(gen_random_uuid(), 'DOUGLAS STAPF AMANCIO', 'douglas stapf amancio', 'Entrenador Extranjero', 'FRANCO BASQUETBOL CLUB RUC 80108342-7'),
(gen_random_uuid(), 'GIZELLE FERNANDES LOPES FALCAO', 'gizelle fernandes lopes falcao', 'Fisio', 'FRANCO BASQUETBOL CLUB  RUC 80108342-7'),
(gen_random_uuid(), 'Hector Joaquin Margosa', 'hector joaquin margosa', 'Entrenador Extranjero', 'Asoc de Ex alumnos del colegio San Jose   RUC 80027202-1'),
(gen_random_uuid(), 'Alexis Daniel Martínez Mongeloz', 'alexis daniel martinez mongeloz', 'Preparador Fisico', 'Club Olimpia 80029733-4'),
(gen_random_uuid(), 'Oscar Toro', 'oscar toro', 'Asistente', '80029128-0 Club Sportivo Luqueño'),
(gen_random_uuid(), 'Facundo Gomez', 'facundo gomez', 'Entrenador Extranjero', 'Facundo Nahuel 9260857'),
(gen_random_uuid(), 'Felix rafael toledo villan', 'felix rafael toledo villan', 'Asistente', 'Club atletico ciudad nueva ruc:80028943-9'),
(gen_random_uuid(), 'Elias Sosa', 'elias sosa', 'Entrenador Nacional', '2331788-4'),
(gen_random_uuid(), 'GUILLERMO ALEJANDRO ARAUJO CAPPELLO', 'guillermo alejandro araujo cappello', 'Entrenador Nacional', 'GUILERMO ALEJANDRO ARAUJO CAPPELLO RUC: 2497825-6'),
(gen_random_uuid(), 'Lucas aballone', 'lucas aballone', 'Entrenador Extranjero', 'no hace falta'),
(gen_random_uuid(), 'Edgar Armando Perez', 'edgar armando perez', 'Entrenador Extranjero', 'Asoc de Ex alumnos del colegio San José  RUC 80027202-1'),
(gen_random_uuid(), 'JUAN MANUEL SANTACRUZ DOS SANTOS', 'juan manuel santacruz dos santos', 'Entrenador Nacional', '1999633-0'),
(gen_random_uuid(), 'Edwar Toledo', 'edwar toledo', 'Fisio', 'Asoc. de Ex Alumnos del Colegio San José / Ruc: 80027202-1'),
(gen_random_uuid(), 'Elvio Zalazar Amarilla', 'elvio zalazar amarilla', 'Entrenador Nacional', '1.163.604'),
(gen_random_uuid(), 'José María Pereira Cristaldo', 'jose maria pereira cristaldo', 'Asistente', 'José Pereira 4479596'),
(gen_random_uuid(), 'Andrea Paola Gomez Caniza', 'andrea paola gomez caniza', 'Entrenador Nacional', 'Deportivo Internacional 80037173-9'),
(gen_random_uuid(), 'Oscar Martínez Torres', 'oscar martinez torres', 'Entrenador Nacional', 'Oscar Martínez - 2.269.670-9'),
(gen_random_uuid(), 'Juan Marcelo Liseras Insfran', 'juan marcelo liseras insfran', 'Entrenador Nacional', 'Depotivo Internacional Ruc: 80037173-9'),
(gen_random_uuid(), 'Rodrigo Daniel Rojas Testa', 'rodrigo daniel rojas testa', 'Entrenador Nacional', 'Rodrigo Daniel Rojas Testa RUC: 2365138-5'),
(gen_random_uuid(), 'Marta Peralta', 'marta peralta', 'Entrenador Nacional', 'Club Deportivo SAJONIA'),
(gen_random_uuid(), 'Sergio Kreizer', 'sergio kreizer', 'Entrenador Extranjero', '2426932-8'),
(gen_random_uuid(), 'Gustavo Paniagua', 'gustavo paniagua', 'Entrenador Nacional', 'Gustavo Paniagua RUC: 3196367'),
(gen_random_uuid(), 'Vicente Raúl Rodríguez Arevalos', 'vicente raul rodriguez arevalos', 'Asistente', 'Club Deportivo internacional 80037173-9'),
(gen_random_uuid(), 'JORGE ADRIAN JARA SALOMON', 'jorge adrian jara salomon', 'Entrenador Nacional', 'JORGE ADRIAN JARA SALOMON 4247914-2'),
(gen_random_uuid(), 'Nelson Enrique Leiva Fritsch', 'nelson enrique leiva fritsch', 'Entrenador Nacional', '3391224-6'),
(gen_random_uuid(), 'Ciro Catriel Lambare Portillo', 'ciro catriel lambare portillo', 'Entrenador Nacional', '3391224-6 Nelson Leiva'),
(gen_random_uuid(), 'Jazmin Mercado', 'jazmin mercado', 'Entrenador Nacional', 'Jazmin Mercado 3641920-6'),
(gen_random_uuid(), 'Niusa Pereira', 'niusa pereira', 'Fisio', 'Asoc de Ex alumnos del colegio San José  RUC 80027202-1'),
(gen_random_uuid(), 'Jesús Gill', 'jesus gill', 'Entrenador Nacional', '.'),
(gen_random_uuid(), 'Luis Ljubetic', 'luis ljubetic', 'Entrenador Nacional', 'Luis ljubetic  2267315-6'),
(gen_random_uuid(), 'Rodrigo Hidalgo', 'rodrigo hidalgo', 'Asistente', 'Club Olimpia 80029733-4'),
(gen_random_uuid(), 'Hugo Marcial Collante Barrios', 'hugo marcial collante barrios', 'Entrenador Nacional', 'Hugo Collante. 2265801-7'),
(gen_random_uuid(), 'Ivan Dario López Espinoza', 'ivan dario lopez espinoza', 'Preparador Fisico', 'Ivan Lopez 5849297-6'),
(gen_random_uuid(), 'Juan Damian Gonzalez Riveros', 'juan damian gonzalez riveros', 'Preparador Fisico', '4467140.0'),
(gen_random_uuid(), 'Melgin Szymanski', 'melgin szymanski', 'Fisio', 'Melgin Szymanski 3441223'),
(gen_random_uuid(), 'Raúl Rolando Alarcón Aránguiz', 'raul rolando alarcon aranguiz', 'Entrenador Extranjero', 'Club Olimpia 80029733-4'),
(gen_random_uuid(), 'Diego Sebastián Medina', 'diego sebastian medina', 'Entrenador Extranjero', 'RUC: 80030665-1'),
(gen_random_uuid(), 'Alexis Daniel Gamarra Chase', 'alexis daniel gamarra chase', 'Entrenador Nacional', 'RUC: 80030665-1'),
(gen_random_uuid(), 'Angela Guadalupe Reyes Torres', 'angela guadalupe reyes torres', 'Asistente', 'RUC: 80030665-1'),
(gen_random_uuid(), 'Juan Pablo Zalazar Vázquez', 'juan pablo zalazar vazquez', 'Entrenador Nacional', 'Club Cerro Porteño de Azucena Cnel Oviedo'),
(gen_random_uuid(), 'Guillermo Eduardo', 'guillermo eduardo', 'Asistente', 'RUC: 80030665-1'),
(gen_random_uuid(), 'Henry Gonthier Leiva Fritsch', 'henry gonthier leiva fritsch', 'Asistente', 'RUC: 80030665-1'),
(gen_random_uuid(), 'RICARDO SEBASTIAN ACEVAL PESOA', 'ricardo sebastian aceval pesoa', 'Entrenador Nacional', 'CLUB SOL DE AMERICA'),
(gen_random_uuid(), 'Fabrizio Alan Chavez', 'fabrizio alan chavez', 'Asistente', 'Colonias Unidas Basquet Club 80117065-1'),
(gen_random_uuid(), 'FRANCO MAXIMILIANO CAZAL CACERES', 'franco maximiliano cazal caceres', 'Asistente', 'YANIK VILLASBOA 1669350-7'),
(gen_random_uuid(), 'MANUEL RIOS', 'manuel rios', 'Entrenador Nacional', 'Club Deportivo Internacional RUC 80037173-9'),
(gen_random_uuid(), 'MARIA JOSE GODOY CRISTALDO', 'maria jose godoy cristaldo', 'Asistente', 'CLUB SOL DE AMERICA'),
(gen_random_uuid(), 'Renso Amaya', 'renso amaya', 'Entrenador Nacional', '80037173-9'),
(gen_random_uuid(), 'Gustavo De Oliveira', 'gustavo de oliveira', 'Entrenador Extranjero', 'Club Deportivo Britanico RUC: 80139193-8'),
(gen_random_uuid(), 'Romina Melgarejo', 'romina melgarejo', 'Fisio', 'Club Deportivo Britanico RUC: 80139193-8'),
(gen_random_uuid(), 'Evert Dominguez', 'evert dominguez', 'Entrenador Nacional', 'Club Deportivo Britanico RUC: 80139193-8'),
(gen_random_uuid(), 'Augusto Meneses', 'augusto meneses', 'Entrenador Extranjero', '80130938-7'),
(gen_random_uuid(), 'Cristian Deleón', 'cristian deleon', 'Asistente', 'Datos para factura Razón social: CLUB DEPORTIVO YACARE  Ruc: *80130938-7*'),
(gen_random_uuid(), 'Marcos Mereles', 'marcos mereles', 'Asistente', 'CLUB DEPORTIVO YACARE  Ruc: *80130938-7*'),
(gen_random_uuid(), 'César Mereles', 'cesar mereles', 'Entrenador Nacional', 'CLUB DEPORTIVO YACARE  Ruc: 80130938-7'),
(gen_random_uuid(), 'Juan Pablo Feliu', 'juan pablo feliu', 'Entrenador Extranjero', 'Datos para factura Razón social: CLUB DEPORTIVO YACARE  Ruc: *80130938-7*'),
(gen_random_uuid(), 'Elizabeth Aguilera', 'elizabeth aguilera', 'Fisio', '4337461-1'),
(gen_random_uuid(), 'Joaquín Duarte', 'joaquin duarte', 'Asistente', 'Augusto Duarte 1996957-0'),
(gen_random_uuid(), 'TAE WON KANG', 'tae won kang', 'Utilero', 'TAE Won Kang - RUC: 1.466.492-5'),
(gen_random_uuid(), 'Jose Alberto Zalazar Vazquez', 'jose alberto zalazar vazquez', 'Asistente', 'Cerro porteño de azucena'),
(gen_random_uuid(), 'Gustavo Estevão Lima', 'gustavo estevao lima', 'Entrenador Extranjero', 'Club Deportivo Britanico RUC: 80139193-8'),
(gen_random_uuid(), 'Romina Melgarejo', 'romina melgarejo', 'Fisio', 'Club Deportivo Britanico RUC: 80139193-8'),
(gen_random_uuid(), 'Sofía Villasboa', 'sofia villasboa', 'Entrenador Nacional', '80030665-1'),
(gen_random_uuid(), 'Guadalupe Reyes', 'guadalupe reyes', 'Asistente', '80030665-1'),
(gen_random_uuid(), 'René Arce', 'rene arce', 'Entrenador Nacional', 'René Arce 929976-9'),
(gen_random_uuid(), 'Rodrigo Adrián Recalde Clemens', 'rodrigo adrian recalde clemens', 'Entrenador Nacional', 'Jorge Ramos 758937-9'),
(gen_random_uuid(), 'Jesús Juan Pablo Aquino', 'jesus juan pablo aquino', 'Asistente', 'Jorge Ramos 758937-9'),
(gen_random_uuid(), 'Mariano Antonio Alfonso', 'mariano antonio alfonso', 'Asistente', 'Jorge Ramos 758937-9'),
(gen_random_uuid(), 'Carlos Federico Ramos Schaefer', 'carlos federico ramos schaefer', 'Asistente', 'Jorge Ramos 758937-9'),
(gen_random_uuid(), 'Roberto Ulices Cardozo Zaldivar', 'roberto ulices cardozo zaldivar', 'Preparador Fisico', 'Roberto Cardozo 3025741-7'),
(gen_random_uuid(), 'Néstor Javier Rolón', 'nestor javier rolon', 'Asistente', 'Club Félix Pérez Cardozo'),
(gen_random_uuid(), 'Isaias Osvaldo Rojas Peña', 'isaias osvaldo rojas pena', 'Fisio', 'COLONIAS UNIDAS BASQUET CLUB 80117060-5'),
(gen_random_uuid(), 'Ilda Carina peña valdez', 'ilda carina pena valdez', 'Asistente', 'Felix  perez cardozo'),
(gen_random_uuid(), 'LIDA FERNÁNDEZ', 'lida fernandez', 'Entrenador Nacional', 'CLUB SOCIAL, CULTURAL Y DEPORTIVO FELIX PEREZ CARDOZO 80030691-0'),
(gen_random_uuid(), 'Silvio Gomez Ramirez', 'silvio gomez ramirez', 'Utilero', 'Jorge Ramos 758937-9'),
(gen_random_uuid(), 'Jorge Luis Ramos', 'jorge luis ramos', 'Fisio', 'Jorge Ramos 758937-9'),
(gen_random_uuid(), 'Monica Schaefer', 'monica schaefer', 'Fisio', 'Jorge Ramos 758937-9'),
(gen_random_uuid(), 'Ana Belen Britez Riveros', 'ana belen britez riveros', 'Asistente', '80030665-1'),
(gen_random_uuid(), 'Luis Carlos Arce', 'luis carlos arce', 'Asistente', 'René Ricardo Tottil Medina 4195596-0');
