// Nacionalidades con Paraguay y vecinos primero, luego orden alfabético
const VECINOS = [
  "Paraguaya",
  "Argentina",
  "Boliviana",
  "Brasileña",
  "Uruguaya",
]

const RESTO = [
  "Afgana", "Albanesa", "Alemana", "Andorrana", "Angoleña", "Antiguana",
  "Argelina", "Armenia", "Australiana", "Austriaca", "Azerbaiyana",
  "Bahameña", "Bareiní", "Bangladesí", "Barbadense", "Belga",
  "Beliceña", "Beninesa", "Bielorrusa", "Birmana", "Bisauguineana",
  "Bosnioherzegovana", "Botswanesa", "Bruneana", "Búlgara", "Burkinesa",
  "Burundesa", "Butanesa",
  "Caboverdiana", "Camboyana", "Camerunesa", "Canadiense", "Catarí",
  "Chadiana", "Chilena", "China", "Chipriota", "Colombiana",
  "Comorense", "Congoleña", "Costarricense", "Croata", "Cubana",
  "Danesa", "Dominicana", "Dominiquesa",
  "Ecuatoriana", "Egipcia", "Emiratí", "Eritrea", "Escocesa",
  "Eslovaca", "Eslovena", "Española", "Estadounidense", "Estonia",
  "Etíope",
  "Fiyiana", "Filipina", "Finlandesa", "Francesa",
  "Gabonesa", "Gambiana", "Georgiana", "Ghanesa", "Granadina",
  "Griega", "Guatemalteca", "Guineana", "Guyanesa",
  "Haitiana", "Hondureña", "Húngara",
  "India", "Indonesia", "Iraní", "Iraquí", "Irlandesa", "Islandesa",
  "Israelí", "Italiana",
  "Jamaiquina", "Japonesa", "Jordana",
  "Kazaja", "Keniana", "Kirguisa", "Kiribatiana", "Kosovar", "Kuwaití",
  "Laosiana", "Lesotense", "Letona", "Libanesa", "Liberiana", "Libia",
  "Liechtensteiniana", "Lituana", "Luxemburguesa",
  "Macedonia del Norte", "Malgache", "Malasia", "Malauí", "Maldiva",
  "Maliense", "Maltesa", "Marfileña", "Marroquí", "Mauriciana",
  "Mauritana", "Mexicana", "Micronesia", "Moldava", "Monegasca",
  "Mongola", "Montenegrina", "Mozambiqueña",
  "Namibia", "Nauruana", "Neerlandesa", "Neozelandesa", "Nepalesa",
  "Nicaragüense", "Nigerina", "Nigeriana", "Norcoreana", "Noruega",
  "Omaní",
  "Pakistaní", "Palauesa", "Palestina", "Panameña", "Papuana",
  "Peruana", "Polaca", "Portuguesa",
  "Ruandesa", "Rumana", "Rusa",
  "Salomonense", "Salvadoreña", "Samoana", "Sanmarinense",
  "Santotomense", "Saudita", "Senegalesa", "Serbia", "Seychellense",
  "Sierraleonesa", "Singapurense", "Siria", "Somalí", "Srilankesa",
  "Suazi", "Sudafricana", "Sudanesa", "Sudsudanesa", "Sueca", "Suiza",
  "Surinamesa",
  "Tailandesa", "Taiwanesa", "Tanzana", "Tayika", "Timorense",
  "Togolesa", "Tongana", "Trinitense", "Tunecina", "Turca",
  "Turcomana", "Tuvaluana",
  "Ucraniana", "Ugandesa", "Uzbeka",
  "Vanuatuense", "Vaticana", "Venezolana", "Vietnamita",
  "Yemení", "Yibutiana",
  "Zambiana", "Zimbabuense",
]

export const NACIONALIDADES = [
  ...VECINOS.map((n) => ({ value: n, label: n, group: "Paraguay y vecinos" })),
  ...RESTO.map((n) => ({ value: n, label: n, group: "Otras nacionalidades" })),
]
